### ISSUE TITLE
Rule for no "NoOp" expressions

### ISSUE THREAD

**Issue by MartinSStewart** [jfmengels/review-simplification#1]
Originally posted here: https://github.com/jfmengels/review-common/issues/2#issue-626408546

I thought of this after finding `x == True` in some code at work. Essentially a rule that removes expressions that have no effect.

Here are some more I've thought of
`x == True` -> `x`
`x /= False` -> `x`
`(\x -> x)` -> ` ` (so long as this doesn't cause the entire expression to evaluate to nothing)
`1 * x` -> `x`
`0 + x` -> `x`
`"" ++ x` -> `x`

**Comment by jfmengels** [comment]
I just noticed I didn't mention in the README I don't plan on maintaining this package myself. I welcome others to create/copy and maintaining this kind of project though!

Sorry to make you open this same issue in multiple repos :sweat_smile:
